version: '2'
services:
  gibbon:
    depends_on:
      - db
    image: kerrongordon/gibbon
    restart: on-failure
    ports:
      - 8080:80
    networks:
      - back
  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      MYSQL_DATABASE: ghost
    networks:
      - back
networks:
  back:
volumes:
  db_data: