version: "3"
services:
  gibbon:
    image: kerrongordon/gibbon
    container_name: gibbon
    network_mode: host
    volumes:
      - my-gibbon:/var/www/site/
    ports:
      - 80:80
    restart: always

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
  my-gibbon: